// Design: Authoritative Broadsheet | Data layer for all 22 UK business bank accounts
// Suitability tags: sole-trader | limited-company | contractor | startup | freelancer | international | high-turnover

export type Suitability =
  | 'sole-trader'
  | 'limited-company'
  | 'contractor'
  | 'startup'
  | 'freelancer'
  | 'international'
  | 'high-turnover';

export interface BankPlan {
  name: string;
  monthlyFee: number | null; // null = free
  freeMonths?: number;
  transactions: string; // e.g. "Free" or "30p each"
  cashDeposit: string;
  overdraft: boolean;
  bestFor: string;
}

export interface BankAccount {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  logoUrl: string;
  logoColor: string; // brand colour for fallback
  type: 'app-only' | 'high-street' | 'challenger';
  rating: number; // out of 5
  reviewCount: number;
  monthlyFee: number | null;
  freeMonths?: number;
  freePeriodNote?: string;
  transactions: string;
  cashDeposit: string;
  overdraft: boolean;
  fscsProtected: boolean;
  internationalPayments: boolean;
  multiCurrency: boolean;
  accountingIntegrations: string[];
  suitability: Suitability[];
  pros: string[];
  cons: string[];
  plans?: BankPlan[];
  affiliateUrl: string;
  featured?: boolean;
  editorChoice?: boolean;
  bestFor?: string;
  openingTime: string; // e.g. "Same day" or "3–5 days"
  minimumDeposit: string;
}

export const banks: BankAccount[] = [
  {
    id: 'starling',
    name: 'Starling Bank',
    slug: 'starling-bank',
    tagline: 'The original app-only business account — free, fast and feature-rich',
    logoUrl: 'https://logo.clearbit.com/starlingbank.com',
    logoColor: '#6935d8',
    type: 'app-only',
    rating: 4.8,
    reviewCount: 12400,
    monthlyFee: 0,
    transactions: 'Free',
    cashDeposit: 'Via Post Office (£3 per deposit)',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent'],
    suitability: ['sole-trader', 'limited-company', 'startup', 'freelancer', 'contractor'],
    pros: [
      'Completely free for most businesses',
      'Instant spending notifications',
      'Built-in invoicing and bookkeeping tools',
      'FSCS protected up to £85,000',
      'Overdraft available',
      'Excellent mobile app (4.9 App Store)',
    ],
    cons: [
      'No physical branches',
      'Cash deposits cost £3 at Post Office',
      'No joint accounts',
    ],
    affiliateUrl: 'https://www.starlingbank.com/business-account/',
    featured: true,
    editorChoice: true,
    bestFor: 'Best Overall',
    openingTime: 'Same day',
    minimumDeposit: 'None',
  },
  {
    id: 'monzo',
    name: 'Monzo Business',
    slug: 'monzo-business',
    tagline: 'Brilliant free tier with powerful paid plans for growing businesses',
    logoUrl: 'https://logo.clearbit.com/monzo.com',
    logoColor: '#ff3464',
    type: 'app-only',
    rating: 4.6,
    reviewCount: 8900,
    monthlyFee: 0,
    transactions: 'Free (Lite) / Unlimited (Pro)',
    cashDeposit: 'Via PayPoint (£1 per deposit)',
    overdraft: false,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent', 'Sage'],
    suitability: ['sole-trader', 'limited-company', 'startup', 'freelancer'],
    plans: [
      { name: 'Lite', monthlyFee: 0, transactions: 'Free', cashDeposit: '£1 via PayPoint', overdraft: false, bestFor: 'Sole traders' },
      { name: 'Pro', monthlyFee: 5, transactions: 'Unlimited free', cashDeposit: '£1 via PayPoint', overdraft: false, bestFor: 'Growing businesses' },
      { name: 'Team', monthlyFee: 15, transactions: 'Unlimited free', cashDeposit: '£1 via PayPoint', overdraft: false, bestFor: 'Teams' },
    ],
    pros: [
      'Free Lite plan available',
      'Excellent expense management',
      'Instant payment notifications',
      'FSCS protected',
      'Strong accounting integrations',
    ],
    cons: [
      'No overdraft facility',
      'Cash deposits via PayPoint only',
      'Pro features require paid plan',
    ],
    affiliateUrl: 'https://monzo.com/business/',
    featured: true,
    bestFor: 'Best for Startups',
    openingTime: 'Same day',
    minimumDeposit: 'None',
  },
  {
    id: 'tide',
    name: 'Tide',
    slug: 'tide',
    tagline: 'Purpose-built for small businesses with smart invoicing and expense tools',
    logoUrl: 'https://logo.clearbit.com/tide.co',
    logoColor: '#00d4b4',
    type: 'app-only',
    rating: 4.3,
    reviewCount: 6200,
    monthlyFee: 0,
    transactions: '20p per transfer (Free plan)',
    cashDeposit: 'Via Post Office (£1 per deposit)',
    overdraft: false,
    fscsProtected: false,
    internationalPayments: false,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    suitability: ['sole-trader', 'limited-company', 'freelancer', 'contractor'],
    plans: [
      { name: 'Free', monthlyFee: 0, transactions: '20p per transfer', cashDeposit: '£1 Post Office', overdraft: false, bestFor: 'Sole traders' },
      { name: 'Plus', monthlyFee: 9.99, transactions: 'Unlimited free', cashDeposit: '£1 Post Office', overdraft: false, bestFor: 'Small businesses' },
      { name: 'Pro', monthlyFee: 18.99, transactions: 'Unlimited free', cashDeposit: 'Free', overdraft: false, bestFor: 'Growing businesses' },
    ],
    pros: [
      'Quick and easy account opening',
      'Excellent invoicing tools built-in',
      'Company formation service available',
      'Strong accounting integrations',
      'Cashback on spending (paid plans)',
    ],
    cons: [
      'Not FSCS protected (e-money institution)',
      'Transaction fees on free plan',
      'No overdraft',
      'No international payments on free plan',
    ],
    affiliateUrl: 'https://www.tide.co/',
    bestFor: 'Best for Invoicing',
    openingTime: 'Same day',
    minimumDeposit: 'None',
  },
  {
    id: 'revolut',
    name: 'Revolut Business',
    slug: 'revolut-business',
    tagline: 'Multi-currency powerhouse for businesses with international operations',
    logoUrl: 'https://logo.clearbit.com/revolut.com',
    logoColor: '#191c1f',
    type: 'app-only',
    rating: 4.4,
    reviewCount: 9100,
    monthlyFee: 0,
    transactions: 'Limited free, then fees',
    cashDeposit: 'Not available',
    overdraft: false,
    fscsProtected: false,
    internationalPayments: true,
    multiCurrency: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    suitability: ['limited-company', 'startup', 'international', 'high-turnover'],
    plans: [
      { name: 'Basic', monthlyFee: 0, transactions: '5 free/month', cashDeposit: 'N/A', overdraft: false, bestFor: 'Very small businesses' },
      { name: 'Grow', monthlyFee: 19, transactions: '100 free/month', cashDeposit: 'N/A', overdraft: false, bestFor: 'Growing businesses' },
      { name: 'Scale', monthlyFee: 79, transactions: '1000 free/month', cashDeposit: 'N/A', overdraft: false, bestFor: 'Scaling businesses' },
      { name: 'Enterprise', monthlyFee: null, transactions: 'Custom', cashDeposit: 'N/A', overdraft: false, bestFor: 'Large businesses' },
    ],
    pros: [
      'Excellent multi-currency accounts (25+ currencies)',
      'Interbank exchange rates',
      'Virtual and physical cards',
      'Expense management tools',
      'API access for automation',
    ],
    cons: [
      'Not FSCS protected',
      'No cash deposits',
      'Customer service can be slow',
      'Free plan very limited',
    ],
    affiliateUrl: 'https://www.revolut.com/business/',
    featured: true,
    bestFor: 'Best for International',
    openingTime: '1–2 days',
    minimumDeposit: 'None',
  },
  {
    id: 'wise',
    name: 'Wise Business',
    slug: 'wise-business',
    tagline: 'Transparent international transfers with real exchange rates',
    logoUrl: 'https://logo.clearbit.com/wise.com',
    logoColor: '#00b9ff',
    type: 'app-only',
    rating: 4.5,
    reviewCount: 7300,
    monthlyFee: 0,
    freePeriodNote: 'One-time £45 account setup fee',
    transactions: 'Low fees per transfer',
    cashDeposit: 'Not available',
    overdraft: false,
    fscsProtected: false,
    internationalPayments: true,
    multiCurrency: true,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['limited-company', 'startup', 'international', 'freelancer'],
    pros: [
      'Hold 40+ currencies in one account',
      'Real mid-market exchange rates',
      'Transparent, low transfer fees',
      'Local bank details in 10+ countries',
      'Batch payments feature',
    ],
    cons: [
      'One-time £45 setup fee',
      'Not FSCS protected',
      'No cash deposits',
      'Not a full business current account',
    ],
    affiliateUrl: 'https://wise.com/gb/business/',
    bestFor: 'Best for FX',
    openingTime: '1–3 days',
    minimumDeposit: '£45 setup fee',
  },
  {
    id: 'anna',
    name: 'ANNA Money',
    slug: 'anna-money',
    tagline: 'AI-powered admin assistant with tax and invoicing built in',
    logoUrl: 'https://logo.clearbit.com/anna.money',
    logoColor: '#ff6b35',
    type: 'app-only',
    rating: 4.2,
    reviewCount: 2100,
    monthlyFee: 0,
    transactions: 'Free (Pay as you go)',
    cashDeposit: 'Via Post Office',
    overdraft: false,
    fscsProtected: false,
    internationalPayments: false,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'freelancer', 'contractor'],
    plans: [
      { name: 'Pay as you go', monthlyFee: 0, transactions: '£0.20 per payment', cashDeposit: 'Via Post Office', overdraft: false, bestFor: 'Very small businesses' },
      { name: 'Business', monthlyFee: 14.90, transactions: 'Unlimited', cashDeposit: 'Via Post Office', overdraft: false, bestFor: 'Growing businesses' },
      { name: 'Big Business', monthlyFee: 49.90, transactions: 'Unlimited', cashDeposit: 'Via Post Office', overdraft: false, bestFor: 'Larger businesses' },
    ],
    pros: [
      'AI-powered tax reminders and filing',
      'Built-in invoicing with automatic chasing',
      'VAT return preparation',
      'Cashback on business spending',
    ],
    cons: [
      'Not FSCS protected',
      'Limited international features',
      'Smaller brand — less established',
    ],
    affiliateUrl: 'https://anna.money/',
    bestFor: 'Best for Sole Traders',
    openingTime: 'Same day',
    minimumDeposit: 'None',
  },
  {
    id: 'zempler',
    name: 'Zempler Bank',
    slug: 'zempler-bank',
    tagline: 'Formerly Cashplus — established challenger bank with credit options',
    logoUrl: 'https://logo.clearbit.com/zemplerbank.com',
    logoColor: '#7b2d8b',
    type: 'challenger',
    rating: 3.9,
    reviewCount: 1800,
    monthlyFee: 0,
    transactions: 'Free',
    cashDeposit: 'Via Post Office',
    overdraft: false,
    fscsProtected: true,
    internationalPayments: false,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'limited-company', 'contractor'],
    pros: [
      'FSCS protected (full bank licence)',
      'No monthly fee option',
      'Business credit card available',
      'Good for businesses with poor credit history',
    ],
    cons: [
      'Less modern app than competitors',
      'Limited international features',
      'Fewer integrations',
    ],
    affiliateUrl: 'https://www.zemplerbank.com/',
    openingTime: '1–2 days',
    minimumDeposit: 'None',
  },
  {
    id: 'cashplus',
    name: 'Cashplus Bank',
    slug: 'cashplus-bank',
    tagline: 'Business account for those who struggle to get accepted elsewhere',
    logoUrl: 'https://logo.clearbit.com/cashplus.com',
    logoColor: '#e31837',
    type: 'challenger',
    rating: 3.7,
    reviewCount: 3200,
    monthlyFee: 9.95,
    transactions: 'Free',
    cashDeposit: 'Via Post Office',
    overdraft: false,
    fscsProtected: true,
    internationalPayments: false,
    multiCurrency: false,
    accountingIntegrations: ['Xero'],
    suitability: ['sole-trader', 'limited-company'],
    pros: [
      'High acceptance rate — no credit check',
      'FSCS protected',
      'Instant account opening',
      'Good for businesses with poor credit',
    ],
    cons: [
      'Monthly fee required',
      'Limited features vs competitors',
      'No international payments',
    ],
    affiliateUrl: 'https://www.cashplus.com/business/',
    openingTime: 'Same day',
    minimumDeposit: 'None',
  },
  {
    id: 'barclays',
    name: 'Barclays Business',
    slug: 'barclays-business',
    tagline: 'The UK\'s most popular business bank with full branch network',
    logoUrl: 'https://logo.clearbit.com/barclays.co.uk',
    logoColor: '#00aeef',
    type: 'high-street',
    rating: 3.8,
    reviewCount: 15600,
    monthlyFee: 0,
    freeMonths: 12,
    freePeriodNote: 'Free for 12 months, then £8.50/month',
    transactions: 'Free (first 12 months)',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    suitability: ['sole-trader', 'limited-company', 'high-turnover', 'contractor'],
    pros: [
      'Extensive branch and ATM network',
      'FSCS protected',
      'Overdraft and lending available',
      'Free for first 12 months',
      'Full range of business banking products',
      'Relationship manager for larger businesses',
    ],
    cons: [
      '£8.50/month after free period',
      'Slower to open than app-only banks',
      'App less polished than challengers',
      'Customer service can be slow',
    ],
    affiliateUrl: 'https://www.barclays.co.uk/business-banking/',
    bestFor: 'Best High Street Bank',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'hsbc',
    name: 'HSBC Business',
    slug: 'hsbc-business',
    tagline: 'Global banking giant with unmatched international capabilities',
    logoUrl: 'https://logo.clearbit.com/hsbc.co.uk',
    logoColor: '#db0011',
    type: 'high-street',
    rating: 3.6,
    reviewCount: 11200,
    monthlyFee: 0,
    freeMonths: 12,
    freePeriodNote: 'Free for 12 months, then £8/month',
    transactions: 'Free (first 12 months)',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    suitability: ['limited-company', 'high-turnover', 'international'],
    pros: [
      'Global network in 64 countries',
      'Excellent international banking',
      'FSCS protected',
      'Full range of business finance products',
      'Free for 12 months',
    ],
    cons: [
      'Complex application process',
      'Monthly fee after free period',
      'App rated lower than challengers',
      'Long branch waiting times',
    ],
    affiliateUrl: 'https://www.business.hsbc.uk/',
    openingTime: '5–7 days',
    minimumDeposit: 'None',
  },
  {
    id: 'natwest',
    name: 'NatWest Business',
    slug: 'natwest-business',
    tagline: 'Award-winning business banking with strong digital tools',
    logoUrl: 'https://logo.clearbit.com/natwest.com',
    logoColor: '#42145f',
    type: 'high-street',
    rating: 3.7,
    reviewCount: 9800,
    monthlyFee: 0,
    freeMonths: 24,
    freePeriodNote: 'Free for 24 months for new businesses, then £8/month',
    transactions: 'Free (first 24 months)',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    suitability: ['sole-trader', 'limited-company', 'startup', 'high-turnover'],
    pros: [
      'Free for 24 months for new businesses',
      'Extensive branch network',
      'FSCS protected',
      'Overdraft and lending available',
      'Good digital banking tools',
      'Dedicated relationship managers',
    ],
    cons: [
      '£8/month after free period',
      'Slower opening than app banks',
      'Variable customer service reviews',
    ],
    affiliateUrl: 'https://www.natwest.com/business.html',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'lloyds',
    name: 'Lloyds Business',
    slug: 'lloyds-business',
    tagline: 'Trusted high street bank with solid business current accounts',
    logoUrl: 'https://logo.clearbit.com/lloydsbank.com',
    logoColor: '#006a4d',
    type: 'high-street',
    rating: 3.6,
    reviewCount: 8400,
    monthlyFee: 0,
    freeMonths: 12,
    freePeriodNote: 'Free for 12 months, then £8.50/month',
    transactions: 'Free (first 12 months)',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    suitability: ['sole-trader', 'limited-company', 'high-turnover'],
    pros: [
      'Large branch network',
      'FSCS protected',
      'Business overdraft available',
      'Free for 12 months',
      'Good range of business finance',
    ],
    cons: [
      'Monthly fee after free period',
      'App less advanced than challengers',
      'Slow application process',
    ],
    affiliateUrl: 'https://www.lloydsbank.com/business/',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'santander',
    name: 'Santander Business',
    slug: 'santander-business',
    tagline: 'Competitive business banking with cashback and rewards',
    logoUrl: 'https://logo.clearbit.com/santander.co.uk',
    logoColor: '#ec0000',
    type: 'high-street',
    rating: 3.5,
    reviewCount: 6700,
    monthlyFee: 7.50,
    transactions: 'Free',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'limited-company', 'high-turnover'],
    pros: [
      'FSCS protected',
      'Cashback on business spending',
      'Overdraft available',
      'Branch network across UK',
    ],
    cons: [
      'Monthly fee from day one',
      'Smaller branch network than Big Four',
      'App needs improvement',
    ],
    affiliateUrl: 'https://www.santander.co.uk/business/',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'metro',
    name: 'Metro Bank Business',
    slug: 'metro-bank-business',
    tagline: 'Seven-day banking with extended opening hours and walk-in service',
    logoUrl: 'https://logo.clearbit.com/metrobankonline.co.uk',
    logoColor: '#d71920',
    type: 'high-street',
    rating: 3.8,
    reviewCount: 4200,
    monthlyFee: 6,
    transactions: 'Free',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'limited-company', 'high-turnover'],
    pros: [
      'Open 7 days a week',
      'Extended opening hours',
      'Walk-in account opening',
      'FSCS protected',
      'Good for cash-heavy businesses',
    ],
    cons: [
      'Monthly fee',
      'Limited to London and South East',
      'Fewer digital features',
    ],
    affiliateUrl: 'https://www.metrobankonline.co.uk/business/',
    openingTime: 'Same day (in branch)',
    minimumDeposit: 'None',
  },
  {
    id: 'co-op',
    name: 'Co-operative Bank Business',
    slug: 'co-operative-bank-business',
    tagline: 'Ethical banking with a strong social conscience',
    logoUrl: 'https://logo.clearbit.com/co-operativebank.co.uk',
    logoColor: '#00539b',
    type: 'high-street',
    rating: 3.5,
    reviewCount: 3100,
    monthlyFee: 7,
    transactions: 'Free',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero'],
    suitability: ['sole-trader', 'limited-company'],
    pros: [
      'Ethical banking policies',
      'FSCS protected',
      'Good for charities and social enterprises',
      'Overdraft available',
    ],
    cons: [
      'Monthly fee',
      'Smaller branch network',
      'Less competitive on features',
      'App less advanced',
    ],
    affiliateUrl: 'https://www.co-operativebank.co.uk/business/',
    openingTime: '5–7 days',
    minimumDeposit: 'None',
  },
  {
    id: 'virgin-money',
    name: 'Virgin Money Business',
    slug: 'virgin-money-business',
    tagline: 'Refreshing approach to business banking with competitive rates',
    logoUrl: 'https://logo.clearbit.com/virginmoney.com',
    logoColor: '#e10a0a',
    type: 'high-street',
    rating: 3.6,
    reviewCount: 2800,
    monthlyFee: 6.50,
    transactions: 'Free',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'limited-company'],
    pros: [
      'FSCS protected',
      'Competitive interest on balances',
      'Good customer service scores',
      'Overdraft available',
    ],
    cons: [
      'Monthly fee',
      'Limited branch network',
      'Fewer digital features than challengers',
    ],
    affiliateUrl: 'https://uk.virginmoney.com/business/',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'countingup',
    name: 'Countingup',
    slug: 'countingup',
    tagline: 'Business account and accounting software combined in one app',
    logoUrl: 'https://logo.clearbit.com/countingup.com',
    logoColor: '#1a1a2e',
    type: 'app-only',
    rating: 4.1,
    reviewCount: 3400,
    monthlyFee: 3,
    transactions: 'Free',
    cashDeposit: 'Via Post Office',
    overdraft: false,
    fscsProtected: false,
    internationalPayments: false,
    multiCurrency: false,
    accountingIntegrations: ['Built-in', 'Xero'],
    suitability: ['sole-trader', 'freelancer', 'contractor'],
    pros: [
      'Built-in accounting software',
      'Automatic tax estimates',
      'Receipt capture',
      'Invoicing built in',
      'Very affordable',
    ],
    cons: [
      'Not FSCS protected',
      'Limited to sole traders and small businesses',
      'No international payments',
      'Monthly fee',
    ],
    affiliateUrl: 'https://countingup.com/',
    bestFor: 'Best for Accounting',
    openingTime: 'Same day',
    minimumDeposit: 'None',
  },
  {
    id: 'airwallex',
    name: 'Airwallex',
    slug: 'airwallex',
    tagline: 'Global business account for e-commerce and international businesses',
    logoUrl: 'https://logo.clearbit.com/airwallex.com',
    logoColor: '#1a56db',
    type: 'app-only',
    rating: 4.3,
    reviewCount: 2100,
    monthlyFee: 0,
    transactions: 'Low fees per transfer',
    cashDeposit: 'Not available',
    overdraft: false,
    fscsProtected: false,
    internationalPayments: true,
    multiCurrency: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Netsuite'],
    suitability: ['limited-company', 'startup', 'international', 'high-turnover'],
    pros: [
      'Collect payments in 130+ countries',
      'Hold 23+ currencies',
      'Competitive FX rates',
      'Virtual cards for teams',
      'API for automation',
    ],
    cons: [
      'Not FSCS protected',
      'No cash deposits',
      'Not ideal for purely domestic businesses',
    ],
    affiliateUrl: 'https://www.airwallex.com/uk/',
    bestFor: 'Best for E-commerce',
    openingTime: '1–2 days',
    minimumDeposit: 'None',
  },
  {
    id: 'clear-business',
    name: 'Clear Business',
    slug: 'clear-business',
    tagline: 'Simple, transparent business banking with no hidden fees',
    logoUrl: 'https://logo.clearbit.com/clearbusiness.co.uk',
    logoColor: '#0066cc',
    type: 'challenger',
    rating: 3.8,
    reviewCount: 890,
    monthlyFee: 0,
    transactions: 'Free',
    cashDeposit: 'Via Post Office',
    overdraft: false,
    fscsProtected: true,
    internationalPayments: false,
    multiCurrency: false,
    accountingIntegrations: ['Xero'],
    suitability: ['sole-trader', 'limited-company'],
    pros: [
      'FSCS protected',
      'No monthly fee',
      'Simple and transparent pricing',
      'Good for small businesses',
    ],
    cons: [
      'Limited features',
      'No international payments',
      'Smaller brand',
    ],
    affiliateUrl: '#',
    openingTime: '1–2 days',
    minimumDeposit: 'None',
  },
  {
    id: 'royal-bank-scotland',
    name: 'Royal Bank of Scotland Business',
    slug: 'royal-bank-of-scotland-business',
    tagline: 'Scotland\'s leading business bank with nationwide digital access',
    logoUrl: 'https://logo.clearbit.com/rbs.co.uk',
    logoColor: '#00539b',
    type: 'high-street',
    rating: 3.6,
    reviewCount: 4100,
    monthlyFee: 0,
    freeMonths: 24,
    freePeriodNote: 'Free for 24 months for new businesses, then £8/month',
    transactions: 'Free (first 24 months)',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    suitability: ['sole-trader', 'limited-company', 'startup'],
    pros: [
      'Free for 24 months for new businesses',
      'FSCS protected',
      'Good branch network in Scotland',
      'Overdraft available',
    ],
    cons: [
      'Monthly fee after free period',
      'Mainly relevant for Scottish businesses',
    ],
    affiliateUrl: 'https://www.rbs.co.uk/business.html',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'bank-of-scotland',
    name: 'Bank of Scotland Business',
    slug: 'bank-of-scotland-business',
    tagline: 'Part of Lloyds Banking Group — solid choice for Scottish businesses',
    logoUrl: 'https://logo.clearbit.com/bankofscotland.co.uk',
    logoColor: '#003087',
    type: 'high-street',
    rating: 3.5,
    reviewCount: 2900,
    monthlyFee: 0,
    freeMonths: 12,
    freePeriodNote: 'Free for 12 months, then £8.50/month',
    transactions: 'Free (first 12 months)',
    cashDeposit: 'Free at branch',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'limited-company'],
    pros: [
      'FSCS protected',
      'Good for Scottish businesses',
      'Overdraft available',
      'Free for 12 months',
    ],
    cons: [
      'Monthly fee after free period',
      'Limited to Scotland primarily',
    ],
    affiliateUrl: 'https://business.bankofscotland.co.uk/',
    openingTime: '3–5 days',
    minimumDeposit: 'None',
  },
  {
    id: 'first-direct',
    name: 'first direct Business',
    slug: 'first-direct-business',
    tagline: 'Award-winning customer service from HSBC\'s digital-first brand',
    logoUrl: 'https://logo.clearbit.com/firstdirect.com',
    logoColor: '#000000',
    type: 'challenger',
    rating: 4.0,
    reviewCount: 1600,
    monthlyFee: 0,
    transactions: 'Free',
    cashDeposit: 'Via HSBC branches',
    overdraft: true,
    fscsProtected: true,
    internationalPayments: true,
    multiCurrency: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    suitability: ['sole-trader', 'limited-company'],
    pros: [
      'Excellent customer service reputation',
      'FSCS protected',
      'No monthly fee',
      'Backed by HSBC infrastructure',
    ],
    cons: [
      'Less feature-rich than pure challengers',
      'No dedicated business app',
    ],
    affiliateUrl: 'https://www.firstdirect.com/',
    openingTime: '2–3 days',
    minimumDeposit: 'None',
  },
];

export const getBankBySlug = (slug: string): BankAccount | undefined =>
  banks.find((b) => b.slug === slug);

export const getFeaturedBanks = (): BankAccount[] =>
  banks.filter((b) => b.featured);

export const getBanksByType = (type: BankAccount['type']): BankAccount[] =>
  banks.filter((b) => b.type === type);

export const getBanksBySuitability = (suitability: Suitability): BankAccount[] =>
  banks.filter((b) => b.suitability.includes(suitability));

export const getTopRatedBanks = (limit = 5): BankAccount[] =>
  [...banks].sort((a, b) => b.rating - a.rating).slice(0, limit);
