// bankData.ts — matches original buscompare data structure exactly
// Logo CDN URLs uploaded from Google favicon service
// suitableFor tags: sole-trader | limited-company | small-business | startup | freelancer | contractor | international | ecommerce | bad-credit | established-business | charity
// accountTypes: current | free | fast-opening | no-credit-check | accounting | cash-deposit | branch-access | overdraft | multi-currency | international | savings | startup | bad-credit | online

const CDN = 'https://d2xsxph8kpxj0f.cloudfront.net/310519663463044688/ARsFo8cnc8CpnHoXXZH5qW';

export interface BankPlan {
  name: string;
  price: string;
  priceNote?: string;
  monthlyFeeNum: number;
  features: string[];
  highlight?: string;
}

export interface BankAccount {
  id: string;
  name: string;
  provider: string;
  slug: string;
  type: 'highstreet' | 'digital' | 'challenger';
  logo: string; // CDN URL
  logoColor: string;
  tagline: string;
  monthlyFee: string;
  monthlyFeeNum: number;
  freeTransfers: string;
  atmWithdrawals: string;
  spendingAbroad: string;
  cashDeposits: string;
  chequeDeposits: boolean;
  overdraft: boolean;
  fscsProtection: boolean;
  accountingIntegrations: string[];
  businessTypes: string[];
  internationalPayments: boolean;
  rating: number;
  ratingLabel: string;
  bestFor: string;
  badge?: string;
  welcomeOffer: string;
  welcomeOfferDetail: string;
  pros: string[];
  cons: string[];
  summary: string;
  plans: BankPlan[];
  affiliateUrl?: string;
  trustpilot?: number;
  appRating?: number;
  openingFee: string;
  creditCheck: boolean;
  suitableFor: string[];
  hasAccounting: boolean;
  hasBranchAccess: boolean;
  hasCashDeposits: boolean;
  hasFastOpening: boolean;
  hasGlobalCurrencyAccounts: boolean;
  hasNoCreditCheck: boolean;
  accountTypes: string[];
}

export const banks: BankAccount[] = [
  {
    id: 'hsbc',
    name: 'HSBC Small Business Banking Account',
    provider: 'HSBC UK',
    slug: 'hsbc-business',
    type: 'highstreet',
    logo: `${CDN}/hsbc_5eb42e7b.png`,
    logoColor: '#DB0011',
    tagline: 'No monthly fee, free UK digital banking, and a £100 Amazon Gift Card',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free (digital banking)',
    atmWithdrawals: '25p + 0.60% fee',
    spendingAbroad: '2.75% non-sterling fee',
    cashDeposits: 'Yes (branch & Post Office)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Partnership', 'LLP'],
    internationalPayments: true,
    rating: 4.5,
    ratingLabel: 'Excellent',
    bestFor: 'High street banking with no monthly fee',
    badge: '#1 Recommended',
    welcomeOffer: '£100 Amazon.co.uk Gift Card',
    welcomeOfferDetail: 'Claim a £100 Amazon.co.uk Gift Card if accepted for a HSBC Small Business Banking Account. Offer ends April 3rd 2026. T&Cs apply.',
    pros: [
      'No monthly account maintenance fee',
      'Free day-to-day digital banking (app & online)',
      '£100 Amazon Gift Card for new customers',
      'Full branch network access across the UK',
      'Business overdraft available (subject to status)',
      'FSCS protected up to £85,000',
    ],
    cons: [
      'ATM withdrawal fees (25p + 0.60%)',
      '2.75% non-sterling transaction fee',
      'CHAPS and international payments carry additional charges',
      'Credit check required for overdraft applications',
    ],
    summary: "HSBC's Small Business Banking Account is a compelling choice for businesses that want the security and breadth of a major high street bank without paying a monthly fee. The free digital banking covers day-to-day transfers via the app and online portal, while the £100 Amazon Gift Card welcome offer adds immediate value.",
    plans: [
      {
        name: 'Small Business Banking Account',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: [
          'Free day-to-day digital banking',
          'App, online, branch & Post Office access',
          'Business overdraft (subject to status)',
          'CHAPS & international payments available',
          'Accounting software integrations',
          'FSCS protected up to £85,000',
          '£100 Amazon Gift Card (new customers, offer ends 3 April 2026)',
        ],
        highlight: 'Best for full-service banking',
      },
      {
        name: 'Business Banking Account',
        price: 'From £8/month',
        priceNote: 'For larger businesses',
        monthlyFeeNum: 8,
        features: [
          'Everything in Small Business Account',
          'Dedicated relationship manager',
          'Higher transaction limits',
          'Enhanced business lending options',
          'Trade finance and international services',
        ],
      },
    ],
    trustpilot: 1.6,
    appRating: 4.7,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'startup', 'established-business', 'partnership'],
    slug: 'lloyds-business',
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: false,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'international', 'online'],
  },
  {
    id: 'worldfirst',
    name: 'WorldFirst Global Business Account',
    provider: 'WorldFirst',
    slug: 'worldfirst-business',
    type: 'digital',
    logo: `${CDN}/worldfirst_5d13238d.png`,
    logoColor: '#0066CC',
    tagline: 'Global business account with local currency accounts in 10+ countries',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free international transfers',
    atmWithdrawals: 'Not available',
    spendingAbroad: 'Competitive FX rates',
    cashDeposits: 'No',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    businessTypes: ['Limited Company', 'International Business', 'E-commerce'],
    internationalPayments: true,
    rating: 4.2,
    ratingLabel: 'Very Good',
    bestFor: 'E-commerce & international trade',
    welcomeOffer: 'No monthly fee',
    welcomeOfferDetail: 'Free global business account with local currency accounts in 10+ countries.',
    pros: [
      'No monthly fee',
      'Local currency accounts in 10+ countries',
      'Competitive FX rates',
      'Ideal for Amazon, eBay, Etsy sellers',
      'No credit check',
    ],
    cons: [
      'Not FSCS protected',
      'No cash deposits or ATM access',
      'Limited UK-specific features',
      'No overdraft',
    ],
    summary: 'WorldFirst is particularly popular with e-commerce sellers on platforms like Amazon, eBay, and Etsy. The ability to receive payments in local currencies and convert at competitive rates makes it a cost-effective solution for businesses with international sales.',
    plans: [
      {
        name: 'Global Business Account',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: ['Local currency accounts (10+ countries)', 'Free international transfers', 'Competitive FX rates', 'E-commerce platform integrations', 'No credit check'],
        highlight: 'Best for e-commerce',
      },
    ],
    trustpilot: 4.7,
    appRating: 4.3,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['limited-company', 'international', 'ecommerce'],
    hasAccounting: false,
    hasBranchAccess: false,
    hasCashDeposits: false,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'multi-currency', 'international', 'fast-opening', 'no-credit-check', 'online'],
  },
  {
    id: 'zempler',
    name: 'Zempler Bank Business Account',
    provider: 'Zempler Bank',
    slug: 'zempler-bank',
    type: 'challenger',
    logo: `${CDN}/zempler_5e4231d0.png`,
    logoColor: '#FF6B35',
    tagline: 'Business banking for all — including those with bad credit history',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: '10 free per month',
    atmWithdrawals: '£1 per withdrawal',
    spendingAbroad: '2.99% non-sterling fee',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Bad Credit', 'Startup'],
    internationalPayments: false,
    rating: 3.8,
    ratingLabel: 'Good',
    bestFor: 'Bad credit or declined elsewhere',
    welcomeOffer: 'No credit check required',
    welcomeOfferDetail: 'Open a business account even with a poor credit history. No credit check required for the basic account.',
    pros: [
      'No credit check for basic account',
      'FSCS protected',
      'Overdraft available',
      'Cash deposits via Post Office',
      'Accessible to businesses declined elsewhere',
    ],
    cons: [
      'Only 10 free transfers per month',
      'Limited accounting integrations',
      'No international payments',
      'Less feature-rich than competitors',
    ],
    summary: 'Zempler Bank (formerly Cashplus) is one of the few UK business banks that will consider applications from businesses with poor credit history. With FSCS protection and an overdraft facility, it provides a genuine banking solution for businesses that have been declined elsewhere.',
    plans: [
      {
        name: 'Go',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: [
          '3 free UK transfers per month',
          'Cash deposits via PayPoint',
          'Debit card included',
          'Online & app banking',
          'FSCS protection up to £85,000',
          'Overdraft available (subject to status)',
        ],
        highlight: 'Best for bad credit',
      },
      {
        name: 'Plus',
        price: '£9.95/month',
        monthlyFeeNum: 9.95,
        features: [
          'Unlimited free UK transfers',
          'Free ATM withdrawals',
          'Priority customer support',
          'Enhanced spending limits',
          'All Go plan features',
        ],
      },
    ],
    trustpilot: 4.0,
    appRating: 3.9,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'bad-credit', 'startup'],
    hasAccounting: false,
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'bad-credit', 'no-credit-check', 'cash-deposit', 'overdraft', 'online'],
  },
  {
    id: 'anna',
    name: 'ANNA Money',
    provider: 'ANNA Money',
    slug: 'anna-money',
    type: 'digital',
    logo: `${CDN}/anna_50590663.png`,
    logoColor: '#FF6B6B',
    tagline: 'Business account with built-in invoicing, tax reminders and AI assistant',
    monthlyFee: 'Free (Pay As You Go) or from £14.90/month',
    monthlyFeeNum: 0,
    freeTransfers: '3 free per month (PAYG)',
    atmWithdrawals: '£1 per withdrawal',
    spendingAbroad: '2% non-sterling fee',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer', 'Startup'],
    internationalPayments: false,
    rating: 4.1,
    ratingLabel: 'Very Good',
    bestFor: 'Invoicing, tax reminders & AI assistant',
    welcomeOffer: 'Free PAYG plan available',
    welcomeOfferDetail: 'Start with a free Pay As You Go plan. No credit check required.',
    pros: [
      'Built-in invoicing and tax reminders',
      'AI assistant for business admin',
      'FSCS protected',
      'No credit check',
      'Fast account opening',
    ],
    cons: [
      'Only 3 free transfers on PAYG plan',
      'No overdraft',
      'No international payments',
      'Monthly plans can be expensive',
    ],
    summary: 'ANNA Money stands out for its built-in business admin tools, including invoicing, tax reminders, and an AI assistant that can help with routine tasks. The free PAYG plan makes it accessible for businesses with low transaction volumes, while the paid plans suit more active businesses.',
    plans: [
      {
        name: 'Pay As You Go',
        price: 'Free',
        priceNote: 'Pay per transaction',
        monthlyFeeNum: 0,
        features: [
          'Basic banking',
          'AI invoicing tools',
          'HMRC tax calculator',
          'Pay per transfer (from 20p)',
          'Cash deposits via PayPoint',
        ],
        highlight: 'Best for startups',
      },
      {
        name: 'Business',
        price: '£22.90+VAT/month',
        monthlyFeeNum: 22.9,
        features: [
          'Unlimited transfers',
          'Cashback on business spending',
          '3 free ATM withdrawals/month',
          'Priority support',
          'All PAYG features',
        ],
        highlight: 'Most popular',
      },
      {
        name: 'Big Business',
        price: '£59.90+VAT/month',
        monthlyFeeNum: 59.9,
        features: [
          'Everything in Business',
          'Higher cashback rates',
          'Dedicated account manager',
          'Advanced analytics',
          'Enhanced limits',
        ],
        highlight: 'Best for growing businesses',
      },
    ],
    trustpilot: 4.5,
    appRating: 4.6,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'freelancer', 'startup'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'free', 'fast-opening', 'no-credit-check', 'accounting', 'cash-deposit', 'online'],
  },
  {
    id: 'wallester',
    name: 'Wallester Business Expense Account',
    provider: 'Wallester',
    slug: 'wallester-business',
    type: 'digital',
    logo: `${CDN}/wallester_ff9ad561.png`,
    logoColor: '#6C47FF',
    tagline: 'Unlimited virtual cards and expense management for teams',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free',
    atmWithdrawals: 'Not available',
    spendingAbroad: 'Free (within limits)',
    cashDeposits: 'No',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    businessTypes: ['Limited Company', 'Small Business'],
    internationalPayments: true,
    rating: 4.0,
    ratingLabel: 'Very Good',
    bestFor: 'Team expense management & virtual cards',
    welcomeOffer: 'Unlimited free virtual cards',
    welcomeOfferDetail: 'Create unlimited virtual cards for your team with no monthly fee.',
    pros: [
      'Unlimited virtual cards',
      'No monthly fee',
      'Good expense management tools',
      'No credit check',
      'Team spending controls',
    ],
    cons: [
      'Not FSCS protected',
      'No cash deposits or ATM access',
      'Not a full business current account',
      'No overdraft',
    ],
    summary: 'Wallester is a business expense management platform rather than a traditional bank account. It excels at helping businesses manage team spending through unlimited virtual cards and real-time expense tracking, making it a useful complement to a main business bank account.',
    plans: [
      {
        name: 'Business Account',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: ['Unlimited virtual cards', 'Team expense management', 'Real-time spending controls', 'Accounting integrations', 'No credit check'],
        highlight: 'Best for team expenses',
      },
    ],
    trustpilot: 4.4,
    appRating: 4.2,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['limited-company', 'small-business'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: false,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'multi-currency', 'no-credit-check', 'online'],
  },
  {
    id: 'lloyds',
    name: 'Lloyds Business Account',
    provider: 'Lloyds Bank',
    slug: 'lloyds-business',
    type: 'highstreet',
    logo: `${CDN}/lloyds_34946849.png`,
    logoColor: '#006A4D',
    tagline: 'Get £200 when you open a Lloyds Business Account',
    monthlyFee: 'Free for 12 months, then £8.50/month',
    monthlyFeeNum: 0,
    freeTransfers: 'Free for 12 months',
    atmWithdrawals: 'Free at Lloyds ATMs',
    spendingAbroad: '2.99% non-sterling fee',
    cashDeposits: 'Yes (branch & Post Office)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Partnership'],
    internationalPayments: true,
    rating: 4.3,
    ratingLabel: 'Very Good',
    bestFor: 'New businesses & traditional banking',
    welcomeOffer: '£200 cashback',
    welcomeOfferDetail: 'Get £200 cashback when you open a Lloyds Business Account. T&Cs apply.',
    pros: [
      '12 months free banking for new businesses',
      '£200 welcome cashback',
      'Full branch network access',
      'FSCS protected up to £85,000',
      'Overdraft available',
      'Good accounting integrations',
    ],
    cons: [
      '£8.50/month after free period',
      '2.99% foreign transaction fee',
      'Credit check required',
    ],
    summary: 'Lloyds Business Account is a solid choice for new businesses wanting traditional high street banking. The 12-month free period and £200 cashback offer make it particularly attractive for startups, while the full branch network provides reassurance for businesses that prefer face-to-face banking.',
    plans: [
      {
        name: 'Business Account',
        price: 'Free for 12 months',
        priceNote: 'Then £8.50/month',
        monthlyFeeNum: 0,
        features: [
          '12 months free banking',
          '100 free electronic payments out per month',
          'App, online & branch access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
          '£200 cashback welcome offer',
          'Accounting software integrations',
        ],
        highlight: 'Best for new businesses',
      },
      {
        name: 'Business Account (after free period)',
        price: '£8.50/month',
        priceNote: 'After 12 months',
        monthlyFeeNum: 8.5,
        features: [
          '100 free electronic payments out per month',
          'App, online & branch access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
          'Accounting software integrations',
          'Relationship manager available',
        ],
      },
    ],
    trustpilot: 1.5,
    appRating: 4.3,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'startup', 'established-business', 'partnership'],
    hasAccounting: true,
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'startup', 'online'],
  },
  {
    id: 'coop',
    name: 'The Co-operative Bank Business Bank Account',
    provider: 'Co-operative Bank',
    slug: 'cooperative-bank',
    type: 'highstreet',
    logo: `${CDN}/coop_b3cf9574.png`,
    logoColor: '#00539F',
    tagline: 'Ethical banking with free day-to-day banking for small businesses',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free (online)',
    atmWithdrawals: 'Free',
    spendingAbroad: '2.75% non-sterling fee',
    cashDeposits: 'Yes (branch & Post Office)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Small Business', 'Charity'],
    internationalPayments: true,
    rating: 3.9,
    ratingLabel: 'Good',
    bestFor: 'Ethical banking & charities',
    welcomeOffer: 'Free day-to-day banking',
    welcomeOfferDetail: 'Free day-to-day banking for small businesses and charities.',
    pros: [
      'No monthly fee',
      'Ethical banking principles',
      'FSCS protected',
      'Branch access',
      'Good for charities and social enterprises',
    ],
    cons: [
      'Limited branch network',
      'Less feature-rich than digital banks',
      '2.75% foreign transaction fee',
    ],
    summary: 'The Co-operative Bank is the UK\'s leading ethical bank, making it particularly popular with charities, social enterprises, and businesses that prioritise ethical values. The free day-to-day banking and FSCS protection make it a solid choice for small businesses and organisations.',
    plans: [
      {
        name: 'Business Current Account',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: ['Free online transfers', 'Branch access', 'FSCS protected', 'Overdraft available', 'Ethical banking principles'],
        highlight: 'Best for ethical businesses',
      },
    ],
    trustpilot: 3.8,
    appRating: 3.9,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'charity', 'partnership'],
    hasAccounting: true,
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'online'],
  },
  {
    id: 'airwallex',
    name: 'Airwallex Business Account',
    provider: 'Airwallex',
    slug: 'airwallex-business',
    type: 'digital',
    logo: `${CDN}/airwallex_4c68b4a6.png`,
    logoColor: '#1A56DB',
    tagline: 'Global business account with no monthly fee and 60+ currencies',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free international transfers',
    atmWithdrawals: 'Not available',
    spendingAbroad: 'Interbank rate + 0.5%',
    cashDeposits: 'No',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'NetSuite'],
    businessTypes: ['Limited Company', 'International Business', 'E-commerce', 'Startup'],
    internationalPayments: true,
    rating: 4.3,
    ratingLabel: 'Very Good',
    bestFor: 'International payments & multi-currency',
    welcomeOffer: 'No monthly fee',
    welcomeOfferDetail: 'Free business account with no monthly fee and access to 60+ currencies.',
    pros: [
      'No monthly fee',
      '60+ currency accounts',
      'Excellent FX rates (interbank + 0.5%)',
      'Fast international transfers',
      'No credit check',
    ],
    cons: [
      'Not FSCS protected',
      'No cash deposits or ATM access',
      'Limited UK-specific features',
      'No overdraft',
    ],
    summary: 'Airwallex is a powerful global business account designed for companies with significant international payment needs. With 60+ currency accounts and near-interbank FX rates, it\'s particularly well-suited to e-commerce businesses and companies with global supply chains.',
    plans: [
      {
        name: 'Explore',
        price: 'Free',
        priceNote: '1 month free trial',
        monthlyFeeNum: 0,
        features: [
          'Free international transfers',
          'Local currency accounts (60+ countries)',
          'Xero, QuickBooks integrations',
          'Virtual cards',
          'Mid-market FX rates',
          'API access',
        ],
        highlight: 'Best for startups',
      },
      {
        name: 'Growth',
        price: 'Custom',
        monthlyFeeNum: 0,
        features: [
          'All Explore features',
          'Higher transfer limits',
          'Dedicated onboarding support',
          'Advanced reporting',
          'Physical cards',
        ],
      },
      {
        name: 'Enterprise',
        price: 'Custom',
        monthlyFeeNum: 0,
        features: [
          'All Growth features',
          'Dedicated account manager',
          'Custom integrations',
          'SLA-backed support',
          'Bespoke solutions',
        ],
        highlight: 'Best for large businesses',
      },
    ],
    trustpilot: 4.5,
    appRating: 4.5,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['limited-company', 'international', 'ecommerce', 'startup'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: false,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'multi-currency', 'international', 'fast-opening', 'no-credit-check', 'online'],
  },
  {
    id: 'tide',
    name: 'Tide Business Bank Account',
    provider: 'Tide',
    slug: 'tide-business',
    type: 'digital',
    logo: `${CDN}/tide_d5081234.png`,
    logoColor: '#00D4AA',
    tagline: 'Get £250 cashback when you open a Tide business bank account',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: '20 free per month, then 20p each',
    atmWithdrawals: '£1 per withdrawal',
    spendingAbroad: '0.5% + £0.20 per transaction',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent', 'Sage'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer', 'Contractor'],
    internationalPayments: false,
    rating: 4.6,
    ratingLabel: 'Excellent',
    bestFor: 'Invoicing, small businesses & fast opening',
    badge: 'Most Popular',
    welcomeOffer: '£250 cashback',
    welcomeOfferDetail: 'Get £250 cashback when you open a Tide business bank account and spend £500 within 30 days. T&Cs apply.',
    pros: [
      'Fast account opening (often same day)',
      'Built-in invoicing tools',
      'No credit check required',
      'FSCS protected up to £85,000',
      'Excellent accounting integrations',
      '£250 welcome cashback offer',
    ],
    cons: [
      'Only 20 free transfers per month',
      'No overdraft facility',
      'No cheque deposits',
      'Limited international payment options',
    ],
    summary: 'Tide is one of the UK\'s most popular digital business bank accounts, particularly for sole traders and small businesses. The fast account opening, built-in invoicing, and generous accounting integrations make it a strong choice for businesses that want to get started quickly.',
    plans: [
      {
        name: 'Free',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: [
          'Free transfers for 1 year, then 20p each',
          'Free Tide Mastercard debit card',
          'Invoicing & payment links',
          'Xero, QuickBooks, FreeAgent integrations',
          'FSCS protection up to £120,000',
          'In-app chat support 24/7',
          '1.75–2.75% FX fee on card payments abroad',
          'Cash deposits: Post Office (0.99%, min £2.50)',
        ],
        highlight: 'Best for startups',
      },
      {
        name: 'Smart',
        price: '£12.49/month',
        priceNote: '+ VAT',
        monthlyFeeNum: 12.49,
        features: [
          '25 free UK transfers per month',
          '0% FX fee on card payments abroad',
          'Cash deposits: Post Office (0.5%, min £2.50)',
          'Priority in-app support',
          '1 free expense card included',
          'All Free plan features',
        ],
      },
      {
        name: 'Pro',
        price: '£24.99/month',
        priceNote: '+ VAT',
        monthlyFeeNum: 24.99,
        features: [
          'Unlimited free UK transfers',
          '0% FX fee on card payments abroad',
          'Cash deposits: Post Office (0.5%, min £2.50)',
          'Phone support (Mon–Fri, 9am–6pm)',
          '2 free expense cards included',
          'All Smart plan features',
        ],
        highlight: 'Best for growing businesses',
      },
      {
        name: 'Max',
        price: '£69.99/month',
        priceNote: '+ VAT',
        monthlyFeeNum: 69.99,
        features: [
          'Unlimited free UK transfers',
          '0% FX fee on card payments abroad',
          '0.5% cashback on eligible purchases',
          '3 free expense cards included',
          'Dedicated member support',
          'Priority phone support',
          'All Pro plan features',
        ],
        highlight: 'Best for cashback',
      },
    ],
    trustpilot: 4.1,
    appRating: 4.6,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'startup', 'freelancer', 'contractor', 'partnership'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'free', 'fast-opening', 'no-credit-check', 'accounting', 'cash-deposit', 'online'],
  },
  {
    id: 'countingup',
    name: 'CountingUp Business Current Account',
    provider: 'CountingUp',
    slug: 'countingup',
    type: 'digital',
    logo: `${CDN}/countingup_c58b4e36.png`,
    logoColor: '#7B2D8B',
    tagline: 'Business account with built-in accounting software — no separate subscription needed',
    monthlyFee: 'From £3/month',
    monthlyFeeNum: 3,
    freeTransfers: 'Unlimited',
    atmWithdrawals: '£1 per withdrawal',
    spendingAbroad: '2% non-sterling fee',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: true,
    accountingIntegrations: ['Built-in accounting', 'Xero (export)'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer', 'Startup'],
    internationalPayments: false,
    rating: 4.1,
    ratingLabel: 'Very Good',
    bestFor: 'Built-in accounting — no Xero subscription needed',
    welcomeOffer: 'Built-in accounting software',
    welcomeOfferDetail: 'Business account with built-in accounting software. No separate Xero or QuickBooks subscription required.',
    pros: [
      'Built-in accounting software included',
      'No separate accounting subscription needed',
      'FSCS protected',
      'No credit check',
      'Fast account opening',
      'Automatic receipt capture',
    ],
    cons: [
      'Monthly fee from £3',
      'No overdraft',
      'No international payments',
      'Limited to sole traders and small companies',
    ],
    summary: 'CountingUp is unique in combining a business current account with built-in accounting software, eliminating the need for a separate Xero or QuickBooks subscription. This makes it particularly cost-effective for sole traders and small businesses that want to manage their finances in one place.',
    plans: [
      {
        name: 'Starter',
        price: '£3/month',
        priceNote: 'For low-volume businesses',
        monthlyFeeNum: 3,
        features: ['Unlimited transfers', 'Built-in accounting', 'Receipt capture', 'FSCS protected', 'No credit check'],
        highlight: 'Best for sole traders',
      },
      {
        name: 'Standard',
        price: '£9/month',
        priceNote: 'For growing businesses',
        monthlyFeeNum: 9,
        features: ['Everything in Starter', 'VAT returns', 'Self-assessment support', 'Multiple team members', 'Priority support'],
        highlight: 'Most popular',
      },
    ],
    trustpilot: 4.3,
    appRating: 4.4,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'freelancer', 'startup', 'partnership'],
    slug: 'monzo-business',
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'free', 'fast-opening', 'no-credit-check', 'accounting', 'cash-deposit', 'online'],
  },
  {
    id: 'virgin',
    name: 'Virgin Money M Account for Business',
    provider: 'Virgin Money',
    slug: 'virgin-money-business',
    type: 'highstreet',
    logo: `${CDN}/virgin_2da1a4db.png`,
    logoColor: '#E10A0A',
    tagline: 'Free day-to-day online business banking with branch access',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free (online)',
    atmWithdrawals: 'Free',
    spendingAbroad: '2.99% non-sterling fee',
    cashDeposits: 'Yes (branch)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer'],
    internationalPayments: true,
    rating: 4.2,
    ratingLabel: 'Very Good',
    bestFor: 'Free banking with cashback perks',
    welcomeOffer: 'Free day-to-day banking',
    welcomeOfferDetail: 'Free day-to-day online business banking with no monthly fee. Branch access available.',
    pros: [
      'No monthly fee',
      'Free online transfers',
      'Branch access via Virgin Money stores',
      'FSCS protected',
      'Cashback on business spending',
    ],
    cons: [
      'Limited branch network compared to big four',
      '2.99% foreign transaction fee',
      'Credit check required',
    ],
    summary: 'Virgin Money\'s M Account for Business offers free day-to-day banking with the added benefit of branch access — a rare combination. The cashback perks on business spending add extra value, making it a strong choice for businesses that want free banking without sacrificing physical access.',
    plans: [
      {
        name: 'M Account for Business',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: [
          'Free day-to-day digital banking',
          '0.25% cashback on debit card purchases',
          '6 months free Xero',
          'App, online & branch access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
          'Free ATM withdrawals',
        ],
        highlight: 'Best for cashback',
      },
      {
        name: 'M Plus Account for Business',
        price: 'Free',
        priceNote: 'Enhanced features',
        monthlyFeeNum: 0,
        features: [
          'All M Account features',
          'Higher cashback rate',
          'Enhanced business insights',
          'Priority customer support',
        ],
      },
    ],
    trustpilot: 1.8,
    appRating: 4.2,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'freelancer', 'partnership'],
    hasAccounting: false,
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'free', 'online'],
  },
  {
    id: 'revolut',
    name: 'Revolut Business',
    provider: 'Revolut',
    slug: 'revolut-business',
    type: 'digital',
    logo: `${CDN}/revolut_9fc0ca0d.png`,
    logoColor: '#191C1F',
    tagline: 'Get £200 when you open a Revolut Business account',
    monthlyFee: 'From £10/month',
    monthlyFeeNum: 10,
    freeTransfers: '5 free per month (Free plan)',
    atmWithdrawals: 'Free up to £200/month',
    spendingAbroad: 'Free up to fair use limit',
    cashDeposits: 'No',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    businessTypes: ['Limited Company', 'International Business', 'E-commerce', 'Startup', 'Contractor'],
    internationalPayments: true,
    rating: 4.4,
    ratingLabel: 'Excellent',
    bestFor: 'Multi-currency & international payments',
    welcomeOffer: '£200 welcome bonus',
    welcomeOfferDetail: 'Get £200 when you open a Revolut Business account and meet the qualifying criteria. T&Cs apply.',
    pros: [
      'Multi-currency accounts (25+ currencies)',
      'Excellent international payment rates',
      'Fast account opening',
      'No credit check required',
      'Powerful expense management tools',
    ],
    cons: [
      'Not FSCS protected',
      'No cash deposits',
      'Monthly fee required for most features',
      'No overdraft facility',
    ],
    summary: 'Revolut Business is the go-to choice for businesses with international operations. The multi-currency accounts, competitive FX rates, and powerful expense management tools make it particularly valuable for e-commerce businesses and companies with overseas suppliers or customers.',
    plans: [
      {
        name: 'Basic',
        price: '£10/month',
        monthlyFeeNum: 10,
        features: [
          '10 free UK transfers per month (then £0.20)',
          '5 free international transfers per month',
          'Multi-currency accounts (30+ currencies)',
          'Accounting integrations (Xero, QuickBooks, Sage)',
          'Virtual and physical debit cards',
          'Expense management tools',
          '£1,000/month fee-free FX allowance',
        ],
        highlight: 'Best for small businesses',
      },
      {
        name: 'Grow',
        price: '£30/month',
        monthlyFeeNum: 30,
        features: [
          '100 free UK transfers per month',
          '10 free international transfers per month',
          '£10,000/month fee-free FX allowance',
          'Advanced analytics and reporting',
          'Bulk payment uploads',
          'Priority customer support',
          'All Basic plan features',
        ],
        highlight: 'Most popular',
      },
      {
        name: 'Scale',
        price: '£90/month',
        monthlyFeeNum: 90,
        features: [
          'Unlimited free UK transfers',
          '50 free international transfers per month',
          '£50,000/month fee-free FX allowance',
          'Dedicated account manager',
          'Advanced API access',
          'Custom approval workflows',
          'All Grow plan features',
        ],
        highlight: 'Best for scaling businesses',
      },
      {
        name: 'Enterprise',
        price: 'Custom pricing',
        monthlyFeeNum: 0,
        features: [
          'Custom transfer allowances',
          'Custom FX allowances',
          'Dedicated relationship manager',
          'Custom integrations and API',
          'SLA-backed support',
          'Bespoke onboarding',
          'All Scale plan features',
        ],
        highlight: 'Best for large businesses',
      },
    ],
    trustpilot: 4.3,
    appRating: 4.7,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['limited-company', 'international', 'ecommerce', 'startup', 'contractor'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: false,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'multi-currency', 'international', 'fast-opening', 'no-credit-check', 'accounting', 'online'],
  },
  {
    id: 'tide-savings',
    name: 'Tide Business Bank Account & Savings Account',
    provider: 'Tide',
    slug: 'tide-savings',
    type: 'digital',
    logo: `${CDN}/tide_d5081234.png`,
    logoColor: '#00D4AA',
    tagline: 'Get £200 cashback and earn up to 4.00% AER on savings',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: '20 free per month, then 20p each',
    atmWithdrawals: '£1 per withdrawal',
    spendingAbroad: '0.5% + £0.20 per transaction',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent', 'Sage'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Startup'],
    internationalPayments: false,
    rating: 4.5,
    ratingLabel: 'Excellent',
    bestFor: 'Business banking + savings in one place',
    welcomeOffer: '£200 cashback + up to 4.00% AER',
    welcomeOfferDetail: 'Get £200 cashback and earn up to 4.00% AER on your savings pot. T&Cs apply.',
    pros: [
      'Earn up to 4.00% AER on savings',
      'Business current account + savings in one app',
      'No credit check required',
      'FSCS protected',
      '£200 welcome cashback',
    ],
    cons: [
      'Only 20 free transfers per month',
      'No overdraft facility',
      'No branch access',
    ],
    summary: 'Tide\'s combined business bank account and savings account is ideal for businesses that want to earn interest on idle cash while keeping everything in one place. The 4.00% AER savings rate is competitive, and the no-credit-check policy makes it accessible to most businesses.',
    plans: [
      {
        name: 'Free + Savings',
        price: 'Free',
        priceNote: 'Current account free',
        monthlyFeeNum: 0,
        features: ['Current account (20 free transfers/month)', 'Savings pot up to 4.00% AER', 'FSCS protected', 'No credit check', '£200 cashback offer'],
        highlight: 'Best for earning interest',
      },
    ],
    trustpilot: 4.1,
    appRating: 4.6,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'startup'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'savings', 'free', 'fast-opening', 'no-credit-check', 'online'],
  },
  {
    id: 'monzo',
    name: 'Monzo Business',
    provider: 'Monzo',
    slug: 'monzo-business',
    type: 'digital',
    logo: `${CDN}/monzo_c1236d74.png`,
    logoColor: '#FF3464',
    tagline: 'Smart business banking with instant notifications and tax pots',
    monthlyFee: 'Free (Lite) or £5/month (Pro)',
    monthlyFeeNum: 0,
    freeTransfers: 'Free',
    atmWithdrawals: 'Free (up to £250/month)',
    spendingAbroad: 'Free (up to fair use)',
    cashDeposits: 'Yes (PayPoint)',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer', 'Startup', 'Contractor'],
    internationalPayments: false,
    rating: 4.3,
    ratingLabel: 'Very Good',
    bestFor: 'Smart banking with tax pots & notifications',
    welcomeOffer: 'Free account available',
    welcomeOfferDetail: 'Open a free Monzo Business Lite account or upgrade to Pro for £5/month for additional features.',
    pros: [
      'Instant spending notifications',
      'Tax pots to set aside VAT/tax',
      'FSCS protected',
      'Fast account opening',
      'Good accounting integrations',
      'Free Lite plan available',
    ],
    cons: [
      'No overdraft facility',
      'No international payments',
      'Cash deposits via PayPoint only (£1 fee)',
      'Pro plan required for some features',
    ],
    summary: 'Monzo Business is popular with freelancers and sole traders who appreciate its smart features, particularly the tax pots that automatically set aside money for VAT and income tax. The free Lite plan makes it accessible, while the Pro plan at £5/month adds accounting integrations and additional features.',
    plans: [
      {
        name: 'Lite',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: [
          'Unlimited free UK transfers',
          'Fee-free spending abroad',
          'Invoicing in the app',
          'Spending categories',
          'FSCS protection up to £85,000',
          'Overdraft (sole traders only)',
        ],
        highlight: 'Best for freelancers',
      },
      {
        name: 'Pro',
        price: '£9/month',
        monthlyFeeNum: 9,
        features: [
          'Everything in Lite',
          'Tax pots (set aside for HMRC)',
          'Xero, FreeAgent, QuickBooks integrations',
          'Accounting software sync',
          'First month free',
        ],
        highlight: 'Most popular',
      },
      {
        name: 'Team',
        price: 'From £25/month',
        monthlyFeeNum: 25,
        features: [
          'Everything in Pro',
          'Multi-user access (up to 5 users)',
          'Expense management',
          'Receipt capture',
          'Shared pots',
          'First month free',
        ],
        highlight: 'Best for teams',
      },
    ],
    trustpilot: 4.4,
    appRating: 4.8,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'freelancer', 'startup', 'contractor'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'free', 'fast-opening', 'accounting', 'cash-deposit', 'online'],
  },
  {
    id: 'barclays',
    name: 'Barclays Business Bank Account',
    provider: 'Barclays',
    slug: 'barclays-business',
    type: 'highstreet',
    logo: `${CDN}/barclays_62ffe07f.png`,
    logoColor: '#00AEEF',
    tagline: '12 months free banking for new businesses with Barclays',
    monthlyFee: 'Free for 12 months, then £8.50/month',
    monthlyFeeNum: 0,
    freeTransfers: 'Free for 12 months',
    atmWithdrawals: 'Free',
    spendingAbroad: '2.99% non-sterling fee',
    cashDeposits: 'Yes (branch & Post Office)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    businessTypes: ['Limited Company', 'Established Business', 'Small Business', 'Sole Trader'],
    internationalPayments: true,
    rating: 4.0,
    ratingLabel: 'Very Good',
    bestFor: 'Established businesses & branch banking',
    welcomeOffer: '12 months free banking',
    welcomeOfferDetail: 'New businesses get 12 months free banking with Barclays. T&Cs apply.',
    pros: [
      '12 months free banking for new businesses',
      'Full branch network access',
      'FSCS protected',
      'Business overdraft available',
      'Strong international banking services',
    ],
    cons: [
      '£8.50/month after free period',
      '2.99% foreign transaction fee',
      'Credit check required',
      'Trustpilot score is low',
    ],
    summary: 'Barclays Business Bank Account is a reliable choice for established businesses that value the security of a major high street bank. The 12-month free period for new businesses, combined with full branch access and FSCS protection, makes it a solid foundation for growing companies.',
    plans: [
      {
        name: 'Start-up Business Bank Account',
        price: 'Free for 12 months',
        priceNote: 'Then £8.50/month',
        monthlyFeeNum: 0,
        features: [
          '12 months free banking',
          'Branch & Post Office access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
          '£400 cashback welcome offer',
          'Accounting software integrations',
        ],
        highlight: 'Best for new businesses',
      },
      {
        name: 'Business Current Account',
        price: '£8.50/month',
        priceNote: 'For established businesses',
        monthlyFeeNum: 8.5,
        features: [
          'Full branch network access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
          'Dedicated relationship manager',
          'Merchant services available',
          'International banking services',
        ],
      },
      {
        name: 'Business Premium Account',
        price: 'Custom',
        monthlyFeeNum: 0,
        features: [
          'All Business Current Account features',
          'Dedicated relationship manager',
          'Enhanced lending options',
          'Premium business support',
          'Trade finance services',
        ],
        highlight: 'Best for larger businesses',
      },
    ],
    trustpilot: 1.7,
    appRating: 4.5,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['limited-company', 'established-business', 'small-business', 'sole-trader', 'partnership'],
    hasAccounting: true,
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'startup', 'online'],
  },
  {
    id: 'natwest',
    name: 'NatWest Start-Up Business Bank Account',
    provider: 'NatWest',
    slug: 'natwest-business',
    type: 'highstreet',
    logo: `${CDN}/natwest_c4082d62.png`,
    logoColor: '#42145F',
    tagline: '24 months free banking for new businesses with NatWest',
    monthlyFee: 'Free for 24 months',
    monthlyFeeNum: 0,
    freeTransfers: 'Free for 24 months',
    atmWithdrawals: 'Free',
    spendingAbroad: '2.75% non-sterling fee',
    cashDeposits: 'Yes (branch & Post Office)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Startup', 'Small Business'],
    internationalPayments: true,
    rating: 4.1,
    ratingLabel: 'Very Good',
    bestFor: 'New businesses — 24 months free banking',
    welcomeOffer: '24 months free banking',
    welcomeOfferDetail: 'New businesses get 24 months of free day-to-day banking with NatWest. T&Cs apply.',
    pros: [
      '24 months free banking for new businesses',
      'Full branch network access',
      'FSCS protected',
      'Business overdraft available',
      'Good accounting integrations',
    ],
    cons: [
      'Monthly fee after free period',
      '2.75% foreign transaction fee',
      'Credit check required',
    ],
    summary: 'NatWest\'s Start-Up Business Bank Account offers one of the longest free banking periods available — 24 months — making it an excellent choice for new businesses. Combined with full branch access and FSCS protection, it provides the security of traditional banking while giving new businesses time to establish themselves.',
    plans: [
      {
        name: 'Start-Up Account (0–24 months)',
        price: 'Free',
        priceNote: 'For businesses trading <12 months',
        monthlyFeeNum: 0,
        features: [
          '24 months free everyday banking',
          'Free FreeAgent accounting software',
          'Branch & Post Office access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
          'Cash deposits available',
        ],
        highlight: 'Best for new businesses',
      },
      {
        name: 'Business Account (after free period)',
        price: '£8/month',
        monthlyFeeNum: 8,
        features: [
          '£0.35 per electronic payment',
          'Free FreeAgent accounting software',
          'Branch & Post Office access',
          'Business overdraft (subject to status)',
          'FSCS protection up to £85,000',
        ],
      },
    ],
    trustpilot: 1.5,
    appRating: 4.4,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['limited-company', 'startup', 'small-business', 'sole-trader', 'partnership'],
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    hasAccounting: true,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'startup', 'online'],
  },
  {
    id: 'rbs',
    name: 'Royal Bank of Scotland Start-Up Business Bank Account',
    provider: 'Royal Bank of Scotland',
    slug: 'rbs-business',
    type: 'highstreet',
    logo: `${CDN}/rbs_3f80dd63.png`,
    logoColor: '#002D72',
    tagline: '24 months free banking for new businesses in Scotland and beyond',
    monthlyFee: 'Free for 24 months',
    monthlyFeeNum: 0,
    freeTransfers: 'Free for 24 months',
    atmWithdrawals: 'Free',
    spendingAbroad: '2.75% non-sterling fee',
    cashDeposits: 'Yes (branch & Post Office)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'Sage', 'FreeAgent'],
    businessTypes: ['Limited Company', 'Startup', 'Small Business', 'Sole Trader'],
    internationalPayments: true,
    rating: 4.0,
    ratingLabel: 'Very Good',
    bestFor: 'Scottish businesses & 24 months free banking',
    welcomeOffer: '24 months free banking',
    welcomeOfferDetail: 'New businesses get 24 months of free day-to-day banking with RBS. T&Cs apply.',
    pros: [
      '24 months free banking for new businesses',
      'Full branch network (especially strong in Scotland)',
      'FSCS protected',
      'Business overdraft available',
      'Good accounting integrations',
    ],
    cons: [
      'Monthly fee after free period',
      '2.75% foreign transaction fee',
      'Credit check required',
    ],
    summary: 'RBS offers the same generous 24-month free banking period as its sister bank NatWest, making it an excellent choice for new businesses in Scotland and the rest of the UK. The strong Scottish branch network is a particular advantage for businesses based in Scotland.',
    plans: [
      {
        name: 'Start-Up Account',
        price: 'Free for 24 months',
        priceNote: 'Then standard fees apply',
        monthlyFeeNum: 0,
        features: ['24 months free banking', 'Branch & Post Office access', 'Overdraft available', 'FSCS protected', 'Accounting integrations'],
        highlight: 'Best for Scottish businesses',
      },
    ],
    trustpilot: 1.5,
    appRating: 4.2,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['limited-company', 'startup', 'small-business', 'sole-trader', 'partnership'],
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    hasAccounting: true,
    accountTypes: ['current', 'branch-access', 'cash-deposit', 'overdraft', 'startup', 'online'],
  },
  {
    id: 'starling',
    name: 'Starling Bank Business Account',
    provider: 'Starling Bank',
    slug: 'starling-bank',
    type: 'digital',
    logo: `${CDN}/starling_988a3194.png`,
    logoColor: '#6935D8',
    tagline: 'Award-winning free business account with no monthly fee',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free',
    atmWithdrawals: 'Free',
    spendingAbroad: 'Free (no foreign transaction fees)',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent', 'Sage'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Startup', 'Freelancer', 'Contractor'],
    internationalPayments: true,
    rating: 4.7,
    ratingLabel: 'Excellent',
    bestFor: 'Free banking with overdraft & no foreign fees',
    welcomeOffer: 'No monthly fee',
    welcomeOfferDetail: 'Completely free business account with no monthly fee, no foreign transaction fees, and an overdraft facility.',
    pros: [
      'Completely free — no monthly fee',
      'No foreign transaction fees',
      'Overdraft available',
      'FSCS protected',
      'Excellent accounting integrations',
      'Award-winning app',
    ],
    cons: [
      'Cash deposits via Post Office only',
      'No cheque deposits',
      'No branch access',
      'International transfers carry a fee',
    ],
    summary: 'Starling Bank Business Account is consistently rated as one of the best free business bank accounts in the UK. The combination of no monthly fee, no foreign transaction fees, an overdraft facility, and FSCS protection makes it hard to beat for most small businesses.',
    plans: [
      {
        name: 'Business Account',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: ['Free UK transfers', 'No foreign transaction fees', 'Overdraft available', 'FSCS protected', 'Xero, QuickBooks, FreeAgent integration'],
        highlight: 'Best overall free account',
      },
    ],
    trustpilot: 4.3,
    appRating: 4.9,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'startup', 'freelancer', 'contractor', 'partnership'],
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    hasAccounting: true,
    accountTypes: ['current', 'free', 'fast-opening', 'accounting', 'cash-deposit', 'online'],
  },
  {
    id: 'wise',
    name: 'Wise Business Account',
    provider: 'Wise',
    slug: 'wise-business',
    type: 'digital',
    logo: `${CDN}/wise_97d64049.png`,
    logoColor: '#9FE870',
    tagline: 'Multi-currency business account with the real exchange rate',
    monthlyFee: 'Free (one-time £45 setup fee)',
    monthlyFeeNum: 0,
    freeTransfers: 'Low-cost international transfers',
    atmWithdrawals: 'Free up to £200/month',
    spendingAbroad: 'Real exchange rate + small fee',
    cashDeposits: 'No',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: false,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer', 'International Business', 'Contractor'],
    internationalPayments: true,
    rating: 4.5,
    ratingLabel: 'Excellent',
    bestFor: 'International payments at the real exchange rate',
    welcomeOffer: 'Real exchange rate',
    welcomeOfferDetail: 'Send and receive money internationally at the real exchange rate with a small transparent fee.',
    pros: [
      'Real exchange rate (mid-market rate)',
      '40+ currency accounts',
      'No monthly fee (one-time setup)',
      'No credit check',
      'Transparent fee structure',
    ],
    cons: [
      '£45 one-time setup fee',
      'Not FSCS protected',
      'No cash deposits',
      'No overdraft',
    ],
    summary: 'Wise Business Account is the gold standard for international payments, offering the real mid-market exchange rate with a small transparent fee. The 40+ currency accounts and no monthly fee (after the one-time £45 setup) make it excellent value for businesses with international payment needs.',
    plans: [
      {
        name: 'Business Account',
        price: 'Free (£45 setup)',
        priceNote: 'One-time setup fee',
        monthlyFeeNum: 0,
        features: ['40+ currency accounts', 'Real exchange rate', 'No monthly fee', 'No credit check', 'Accounting integrations'],
        highlight: 'Best for international payments',
      },
    ],
    trustpilot: 4.3,
    appRating: 4.7,
    openingFee: '£45 (one-time)',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'freelancer', 'international', 'contractor'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: false,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'multi-currency', 'international', 'fast-opening', 'no-credit-check', 'online'],
  },
  {
    id: 'cynergy',
    name: 'Cynergy Bank Business Current Account',
    provider: 'Cynergy Bank',
    slug: 'cynergy-bank',
    type: 'highstreet',
    logo: `${CDN}/cynergy_192104fe.png`,
    logoColor: '#00A651',
    tagline: 'Relationship banking with competitive savings rates for UK businesses',
    monthlyFee: 'From £6/month',
    monthlyFeeNum: 6,
    freeTransfers: 'Free (online)',
    atmWithdrawals: 'Free',
    spendingAbroad: '2.75% non-sterling fee',
    cashDeposits: 'Yes (branch)',
    chequeDeposits: true,
    overdraft: true,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Small Business'],
    internationalPayments: true,
    rating: 3.9,
    ratingLabel: 'Good',
    bestFor: 'Relationship banking & competitive savings',
    welcomeOffer: 'Competitive savings rates',
    welcomeOfferDetail: 'Access competitive savings rates alongside your business current account.',
    pros: [
      'FSCS protected',
      'Relationship banking approach',
      'Competitive savings rates',
      'Branch access',
      'Overdraft available',
    ],
    cons: [
      'Monthly fee from £6',
      'Limited branch network',
      'Less well-known brand',
    ],
    summary: 'Cynergy Bank offers a relationship banking approach that is increasingly rare in the UK market. With FSCS protection, competitive savings rates, and a dedicated relationship manager, it suits established businesses that value personal service over digital-first convenience.',
    plans: [
      {
        name: 'Business Current Account',
        price: 'From £6/month',
        priceNote: 'Relationship banking',
        monthlyFeeNum: 6,
        features: ['Relationship manager', 'Branch access', 'Competitive savings rates', 'FSCS protected', 'Overdraft available'],
      },
    ],
    trustpilot: 4.2,
    appRating: 3.8,
    openingFee: 'Free',
    creditCheck: true,
    suitableFor: ['sole-trader', 'limited-company', 'small-business', 'partnership'],
    hasBranchAccess: true,
    hasCashDeposits: true,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: false,
    hasAccounting: true,
    accountTypes: ['current', 'savings', 'online'],
  },
  {
    id: 'equals',
    name: 'Equals Money Multi-Currency Account',
    provider: 'Equals Money',
    slug: 'equals-money',
    type: 'digital',
    logo: `${CDN}/wise_97d64049.png`, // fallback to wise logo as equals logo was too small
    logoColor: '#00B4D8',
    tagline: 'Multi-currency business account with competitive FX rates',
    monthlyFee: 'From £20/month',
    monthlyFeeNum: 20,
    freeTransfers: 'Free international transfers',
    atmWithdrawals: 'Not available',
    spendingAbroad: 'Competitive FX rates',
    cashDeposits: 'No',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: false,
    accountingIntegrations: ['Xero', 'QuickBooks'],
    businessTypes: ['Limited Company', 'International Business', 'E-commerce'],
    internationalPayments: true,
    rating: 3.9,
    ratingLabel: 'Good',
    bestFor: 'Multi-currency payments & FX',
    welcomeOffer: 'Competitive FX rates',
    welcomeOfferDetail: 'Access competitive FX rates and multi-currency accounts for your business.',
    pros: [
      'Multi-currency accounts',
      'Competitive FX rates',
      'Dedicated account manager',
      'No credit check',
      'Good for international businesses',
    ],
    cons: [
      'Not FSCS protected',
      'Monthly fee from £20',
      'No cash deposits',
      'No overdraft',
    ],
    summary: 'Equals Money provides multi-currency business accounts with competitive FX rates, making it suitable for businesses with significant international payment needs. The dedicated account manager adds a personal touch that is increasingly rare in the digital banking space.',
    plans: [
      {
        name: 'Business Account',
        price: 'From £20/month',
        priceNote: 'Multi-currency',
        monthlyFeeNum: 20,
        features: ['Multi-currency accounts', 'Competitive FX rates', 'Dedicated account manager', 'International transfers', 'No credit check'],
      },
    ],
    trustpilot: 4.3,
    appRating: 4.0,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['limited-company', 'international', 'ecommerce'],
    hasAccounting: false,
    hasBranchAccess: false,
    hasCashDeposits: false,
    hasFastOpening: false,
    hasGlobalCurrencyAccounts: true,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'multi-currency', 'international', 'no-credit-check', 'online'],
  },
  {
    id: 'mettle',
    name: 'Mettle by NatWest',
    provider: 'Mettle (NatWest)',
    slug: 'mettle',
    type: 'digital',
    logo: `${CDN}/mettle_3036b78f.png`,
    logoColor: '#1A1A2E',
    tagline: 'Free business account backed by NatWest with built-in invoicing',
    monthlyFee: 'Free',
    monthlyFeeNum: 0,
    freeTransfers: 'Free',
    atmWithdrawals: 'Free',
    spendingAbroad: 'Free (no foreign transaction fees)',
    cashDeposits: 'Yes (Post Office)',
    chequeDeposits: false,
    overdraft: false,
    fscsProtection: true,
    accountingIntegrations: ['Xero', 'QuickBooks', 'FreeAgent'],
    businessTypes: ['Sole Trader', 'Limited Company', 'Freelancer', 'Startup'],
    internationalPayments: false,
    rating: 4.2,
    ratingLabel: 'Very Good',
    bestFor: 'Free banking backed by NatWest',
    welcomeOffer: 'No monthly fee',
    welcomeOfferDetail: 'Free business account backed by NatWest with built-in invoicing and no foreign transaction fees.',
    pros: [
      'Completely free — no monthly fee',
      'Backed by NatWest (FSCS protected)',
      'Built-in invoicing',
      'No foreign transaction fees',
      'Good accounting integrations',
    ],
    cons: [
      'No overdraft facility',
      'No international payments',
      'No branch access',
      'Less well-known than parent brand',
    ],
    summary: 'Mettle is NatWest\'s digital-first business banking brand, offering a free account with the security of FSCS protection and the backing of one of the UK\'s largest banks. The built-in invoicing and no foreign transaction fees make it a strong choice for freelancers and small businesses.',
    plans: [
      {
        name: 'Business Account',
        price: 'Free',
        priceNote: 'No monthly fee',
        monthlyFeeNum: 0,
        features: ['Free UK transfers', 'No foreign transaction fees', 'Built-in invoicing', 'FSCS protected', 'Accounting integrations'],
        highlight: 'Best for free banking with NatWest backing',
      },
    ],
    trustpilot: 4.4,
    appRating: 4.5,
    openingFee: 'Free',
    creditCheck: false,
    suitableFor: ['sole-trader', 'limited-company', 'freelancer', 'startup'],
    hasAccounting: true,
    hasBranchAccess: false,
    hasCashDeposits: true,
    hasFastOpening: true,
    hasGlobalCurrencyAccounts: false,
    hasNoCreditCheck: true,
    accountTypes: ['current', 'free', 'accounting', 'cash-deposit', 'online'],
  }
];

// Helper: get banks by accountType
export function getBanksByType(type: string): BankAccount[] {
  return banks.filter(b => b.accountTypes.includes(type));
}

// Helper: get banks by suitableFor
export function getBanksBySuitability(suitability: string): BankAccount[] {
  return banks.filter(b => b.suitableFor.includes(suitability));
}

// Helper: get bank by slug
export function getBankBySlug(slug: string): BankAccount | undefined {
  return banks.find(b => b.slug === slug);
}

// Category definitions for the category grid
export interface AccountTypeCategory {
  type: string;
  label: string;
  icon: string;
  description: string;
  suitability?: string;
}

export const accountTypeCategories: AccountTypeCategory[] = [
  { type: 'fast-opening', label: 'Fast Opening', icon: '⚡', description: 'Open your account the same day' },
  { type: 'accounting', label: 'With Accountancy', icon: '📊', description: 'Xero, QuickBooks & FreeAgent integrations' },
  { type: 'cash-deposit', label: 'Cash Deposits', icon: '💵', description: 'Deposit cash at Post Office or branch' },
  { type: 'branch-access', label: 'Branch Access', icon: '🏦', description: 'Visit a branch in person' },
  { type: 'freelancer', label: 'Freelancer Accounts', icon: '💻', description: 'Ideal for self-employed individuals', suitability: 'freelancer' },
  { type: 'startup', label: 'Startup Accounts', icon: '🚀', description: 'Free periods for new businesses' },
  { type: 'free', label: 'Free Accounts', icon: '🆓', description: 'No monthly fee' },
  { type: 'joint', label: 'Joint Accounts', icon: '🤝', description: 'Shared business accounts', suitability: 'limited-company' },
  { type: 'overdraft', label: 'With Overdraft', icon: '💳', description: 'Arranged overdraft available' },
  { type: 'online', label: 'Online Accounts', icon: '🌐', description: 'Manage everything online' },
  { type: 'sole-trader', label: 'Sole Trader Accounts', icon: '👤', description: 'Best for self-employed', suitability: 'sole-trader' },
  { type: 'multi-director', label: 'Multi-Director', icon: '👥', description: 'Multiple signatories', suitability: 'limited-company' },
  { type: 'no-credit-check', label: 'No Credit Check', icon: '✅', description: 'No credit check required' },
  { type: 'switcher', label: 'Switcher Accounts', icon: '🔄', description: 'Switch your existing account', suitability: 'established-business' },
  { type: 'small-business', label: 'Small Business', icon: '🏪', description: 'For established small businesses', suitability: 'small-business' },
  { type: 'bad-credit', label: 'Bad Credit', icon: '🔓', description: 'For businesses with poor credit history' },
  { type: 'corporate', label: 'Corporate Accounts', icon: '🏢', description: 'For larger businesses', suitability: 'established-business' },
  { type: 'international', label: 'International', icon: '🌍', description: 'International payments & FX' },
  { type: 'multi-currency', label: 'Multi-Currency', icon: '💱', description: 'Hold multiple currencies' },
];

// Business type cards for homepage
export const businessTypeCards = [
  { title: 'Sole Trader', href: '/category/sole-trader', icon: '👤', desc: 'Best accounts for self-employed individuals', color: 'oklch(0.93 0.04 210)', suitability: 'sole-trader' },
  { title: 'Limited Company', href: '/category/limited-company', icon: '🏢', desc: 'Accounts for Ltd companies', color: 'oklch(0.93 0.04 240)', suitability: 'limited-company' },
  { title: 'Contractor', href: '/category/contractor', icon: '🔧', desc: 'Contractor-friendly banking', color: 'oklch(0.93 0.04 60)', suitability: 'contractor' },
  { title: 'Freelancer', href: '/category/freelancer', icon: '💻', desc: 'Self-employed banking solutions', color: 'oklch(0.93 0.04 290)', suitability: 'freelancer' },
  { title: 'Startup', href: '/category/startup', icon: '🚀', desc: 'New business bank accounts', color: 'oklch(0.93 0.04 25)', suitability: 'startup' },
  { title: 'Small Business', href: '/category/small-business', icon: '🏪', desc: 'For established small businesses', color: 'oklch(0.93 0.04 45)', suitability: 'small-business' },
  { title: 'Partnership', href: '/category/partnership', icon: '🤝', desc: 'Joint business accounts', color: 'oklch(0.93 0.04 162)', suitability: 'partnership' },
  { title: 'E-commerce', href: '/category/ecommerce', icon: '🛒', desc: 'Multi-currency and payment integrations', color: 'oklch(0.95 0.04 45)', suitability: 'ecommerce' },
];

// Guide articles
export const guides = [
  { title: 'How to Open a Business Bank Account', href: '/guides/how-to-open-business-bank-account', icon: '📋', time: '5 min read' },
  { title: 'Business Account vs Personal Account', href: '/guides/business-vs-personal-account', icon: '⚖️', time: '4 min read' },
  { title: 'FSCS Protection Explained', href: '/guides/fscs-protection', icon: '🛡️', time: '3 min read' },
  { title: 'How to Switch Your Business Account', href: '/guides/switch-business-bank-account', icon: '🔄', time: '4 min read' },
  { title: 'Digital vs High Street Banks', href: '/guides/digital-vs-high-street', icon: '🏦', time: '6 min read' },
  { title: 'Business Bank Account Fees Guide', href: '/guides/business-bank-account-fees', icon: '💰', time: '5 min read' },
];
